sudo: false
language: node_js
node_js:
  - '8.0'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false

before_script: npm install -g parcel-bundler
script: parcel build src/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master